### PR TITLE
Update the eslint config

### PR DESCRIPTION
**Pull request by kristenmills**
Update this to basically what's in one repo. Some minor differences, mostly removing stuff we weren't violating...and `arrow-body-style` is back on.

### CODE REVIEW

**Comment by kristenmills** [comment]
Opening the floor for rule proposals as well.

**Comment by vuzDylan** [comment]
I kinda like leaving max length at like 100 - 180 so that if you have really really long lines it tells you but thats just a me thing

**Comment by vuzDylan** [comment]
other than that seems fine :space_invader:

**Review by vuzDylan — APPROVED** [review]

**Review by billdybas — APPROVED** [review]
I'm a recent convert to [Standard](https://standardjs.com/), but Airbnb works for me if that's the style of our current codebase and what you all like using.

**Pull request merged**
